# version: '3.8'

services:
  app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
      - "19000:19000"  # Expo dev server
      - "19001:19001"  # Expo dev tools
      - "19002:19002"  # Expo dev tools
      - "19006:19006"  # Metro bundler
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.expo
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_DEV_SERVER_ORIGIN=http://localhost:19000
      - EXPO_TUNNEL_SUBDOMAIN=event-notification
      - EXPO_DEBUG=false
      - EXPO_NO_WARNINGS=1
      - EXPO_NO_TTY=1
    stdin_open: true  # Keep STDIN open for interactive mode
    tty: true         # Allocate a pseudo-TTY
    # depends_on:
    #   - backend

#   backend:
#     build: 
#       context: ./backend
#       dockerfile: Dockerfile.dev
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./backend:/app
#       - /app/node_modules
#     environment:
#       - NODE_ENV=development
#       - MONGODB_URI=mongodb://mongodb:27017/eventdb
#     depends_on:
#       - mongodb

#   mongodb:
#     image: mongo:6.0
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#     restart: always

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
#       - backend

# volumes:
#   mongodb_data:
